# Generated by Django 5.0.4 on 2024-04-23 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("TEACHER", "Teacher"), ("STUDENT", "Student")],
                default="STUDENT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="students",
            field=models.ManyToManyField(
                related_name="teachers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
