# Generated by Django 5.0.4 on 2024-04-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_role_user_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="key",
            field=models.CharField(max_length=8, null=True),
        ),
    ]
