# Generated by Django 5.0.3 on 2024-04-07 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="practice",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="help",
            name="practice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="learning.practice"
            ),
        ),
        migrations.AddField(
            model_name="constanttext",
            name="practice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="learning.practice"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="practice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="learning.practice"
            ),
        ),
    ]
