# Generated by Django 5.0.4 on 2024-04-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0003_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="variable_max",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="variable_min",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
