# Generated by Django 5.0.4 on 2024-04-23 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_homework_samplehomework_samplequestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="samplehomework",
            name="base_homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="learning.homework"
            ),
        ),
        migrations.AlterField(
            model_name="samplequestion",
            name="base_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="learning.question"
            ),
        ),
    ]
