# Generated by Django 5.0.4 on 2024-04-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_homeworkanswer_questionanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplequestion",
            name="number",
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
