# Generated by Django 5.0.4 on 2024-04-29 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0009_samplequestion_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswer",
            name="homework_answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="learning.homeworkanswer",
            ),
        ),
        migrations.AlterField(
            model_name="samplequestion",
            name="homework",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="learning.samplehomework",
            ),
        ),
    ]
