# Generated by Django 5.0.4 on 2024-05-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0011_questionanswer_evaluation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionanswer",
            name="answer",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
