# Generated by Django 5.0.4 on 2024-05-06 06:57

from django.db import migrations

def create_through_relations(apps, schema_editor):
    HomeWork = apps.get_model('learning', 'HomeWork')
    Containing = apps.get_model('learning', 'Containing')
    for homework in HomeWork.objects.all():
        for idx, question in enumerate(homework.questions.all(), start=1):
            Containing(
                question=question,
                homework=homework,
                number=idx
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0013_containing"),
    ]

    operations = [
        migrations.RunPython(create_through_relations, reverse_code=migrations.RunPython.noop),
    ]
