# Generated by Django 5.0.4 on 2024-05-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0014_auto_20240506_0657"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="questions",
        ),
    ]
