# Generated by Django 5.0.4 on 2024-05-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0016_homework_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="containing",
            name="score",
            field=models.FloatField(default=1),
        ),
    ]
