# Generated by Django 5.0.4 on 2024-05-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0017_containing_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="total_score",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
