# Generated by Django 5.0.4 on 2024-05-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0019_rename_percent_homeworkanswer_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="samplequestion",
            name="number",
        ),
    ]
