# Generated by Django 5.0.4 on 2024-05-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0020_remove_samplequestion_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="delay_score",
            field=models.FloatField(default=0.8),
        ),
        migrations.AddField(
            model_name="homework",
            name="publish_date_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="homework",
            name="publish_date_start",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="homework",
            name="with_delay",
            field=models.BooleanField(default=True),
        ),
    ]
