# Generated by Django 5.0.4 on 2024-05-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0021_homework_delay_score_homework_publish_date_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkanswer",
            name="with_delay",
            field=models.BooleanField(default=False),
        ),
    ]
