# Generated by Django 5.0.4 on 2024-05-15 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0022_homeworkanswer_with_delay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="publish_date_end",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="homework",
            name="publish_date_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
