# Generated by Django 5.0.4 on 2024-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0024_rename_score_homeworkanswer_raw_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="samplequestion",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="samplequestion",
            name="score",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
